language: csharp
mono: none
dotnet: 6.0.300
solution: EFTimestamps.sln
script:
  - dotnet restore
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./coverage/lcov-coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
